export enum ActionType {
    CREATE_TRANSACTION = "CREATE_TRANSACTION",
    DELETE_TRANSACTION = "DELETE_TRANSACTION",
    POPULATE_TRANSACTIONS = "POPULATE_TRANSACTIONS",
    ADD_USER = "ADD_USER",
    CLEAR_STATE = "CLEAR_STATE",
}
